\c testdb testusr

--
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: testusr
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO testusr;

--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: testusr
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: testusr
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    "Discriminator" text NOT NULL
);


ALTER TABLE public."AspNetRoles" OWNER TO testusr;

--
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: testusr
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO testusr;

--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: testusr
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: testusr
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO testusr;

--
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: testusr
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO testusr;

--
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: testusr
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO testusr;

--
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: testusr
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    "Discriminator" text NOT NULL,
    name text
);


ALTER TABLE public."AspNetUsers" OWNER TO testusr;

--
-- Name: BOOK; Type: TABLE; Schema: public; Owner: testusr
--

CREATE TABLE public."BOOK" (
    "Id" integer NOT NULL,
    "Title" character varying(50),
    "Isbn" character varying(20),
    "FormatId" integer NOT NULL,
    "CategoryId" integer NOT NULL
);


ALTER TABLE public."BOOK" OWNER TO testusr;

--
-- Name: BOOK_Id_seq; Type: SEQUENCE; Schema: public; Owner: testusr
--

ALTER TABLE public."BOOK" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."BOOK_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: CATEGORY_MASTER; Type: TABLE; Schema: public; Owner: testusr
--

CREATE TABLE public."CATEGORY_MASTER" (
    "Id" integer NOT NULL,
    "Name" text
);


ALTER TABLE public."CATEGORY_MASTER" OWNER TO testusr;

--
-- Name: CATEGORY_MASTER_Id_seq; Type: SEQUENCE; Schema: public; Owner: testusr
--

ALTER TABLE public."CATEGORY_MASTER" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CATEGORY_MASTER_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: FORMAT_MASTER; Type: TABLE; Schema: public; Owner: testusr
--

CREATE TABLE public."FORMAT_MASTER" (
    "Id" integer NOT NULL,
    "Name" text
);


ALTER TABLE public."FORMAT_MASTER" OWNER TO testusr;

--
-- Name: FORMAT_MASTER_Id_seq; Type: SEQUENCE; Schema: public; Owner: testusr
--

ALTER TABLE public."FORMAT_MASTER" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."FORMAT_MASTER_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: testusr
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: testusr
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- Name: BOOK_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: testusr
--

SELECT pg_catalog.setval('public."BOOK_Id_seq"', 1, true);


--
-- Name: CATEGORY_MASTER_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: testusr
--

SELECT pg_catalog.setval('public."CATEGORY_MASTER_Id_seq"', 1, true);


--
-- Name: FORMAT_MASTER_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: testusr
--

SELECT pg_catalog.setval('public."FORMAT_MASTER_Id_seq"', 1, true);


--
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: testusr
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: testusr
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: testusr
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: testusr
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: testusr
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: testusr
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: testusr
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- Name: BOOK PK_BOOK; Type: CONSTRAINT; Schema: public; Owner: testusr
--

ALTER TABLE ONLY public."BOOK"
    ADD CONSTRAINT "PK_BOOK" PRIMARY KEY ("Id");


--
-- Name: CATEGORY_MASTER PK_CATEGORY_MASTER; Type: CONSTRAINT; Schema: public; Owner: testusr
--

ALTER TABLE ONLY public."CATEGORY_MASTER"
    ADD CONSTRAINT "PK_CATEGORY_MASTER" PRIMARY KEY ("Id");


--
-- Name: FORMAT_MASTER PK_FORMAT_MASTER; Type: CONSTRAINT; Schema: public; Owner: testusr
--

ALTER TABLE ONLY public."FORMAT_MASTER"
    ADD CONSTRAINT "PK_FORMAT_MASTER" PRIMARY KEY ("Id");


--
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: testusr
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: testusr
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: testusr
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: testusr
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: testusr
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- Name: IX_BOOK_CategoryId; Type: INDEX; Schema: public; Owner: testusr
--

CREATE INDEX "IX_BOOK_CategoryId" ON public."BOOK" USING btree ("CategoryId");


--
-- Name: IX_BOOK_FormatId; Type: INDEX; Schema: public; Owner: testusr
--

CREATE INDEX "IX_BOOK_FormatId" ON public."BOOK" USING btree ("FormatId");


--
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: testusr
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: testusr
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: testusr
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: testusr
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: testusr
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: testusr
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: testusr
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: testusr
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: BOOK FK_BOOK_CATEGORY_MASTER_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: testusr
--

ALTER TABLE ONLY public."BOOK"
    ADD CONSTRAINT "FK_BOOK_CATEGORY_MASTER_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."CATEGORY_MASTER"("Id") ON DELETE CASCADE;


--
-- Name: BOOK FK_BOOK_FORMAT_MASTER_FormatId; Type: FK CONSTRAINT; Schema: public; Owner: testusr
--

ALTER TABLE ONLY public."BOOK"
    ADD CONSTRAINT "FK_BOOK_FORMAT_MASTER_FormatId" FOREIGN KEY ("FormatId") REFERENCES public."FORMAT_MASTER"("Id") ON DELETE CASCADE;
