\c testdb testusr

create table book (id integer generated by default as identity, title varchar (255), isbn varchar (255), category_id integer, format_id integer, primary key (id));
create table category_master (id integer generated by default as identity, name varchar (255), primary key (id));
create table format_master (id integer generated by default as identity, name varchar (255), primary key (id));

alter table book add constraint FKpl6tm7wssv8rcu50kxv7xy6aj foreign key (category_id) references category_master;
alter table book add constraint FK8p0xjh0oro1bd7yf7da51fntn foreign key (format_id) references format_master;